### ISSUE TITLE
plugin stopped working

### ISSUE THREAD

**Issue by ralyodio** [eracknaphobia/plugin.video.livestream#1]
I'm using version 2015.8.13

The one in the kodi repo is outdated I guess? Where can I install the latest version?

edit: I downloaded as zip and installed, the search does not work on latest version.

**Comment by ralyodio** [comment]
``````
17:35:24 T:1551830504  NOTICE: -->Python Interpreter Initialized<--
17:35:24 T:1551830504  NOTICE: Mode: 102
17:35:24 T:1551830504  NOTICE: Name: Search Live
17:35:24 T:1551830504  NOTICE: Event ID:None
17:35:24 T:1551830504  NOTICE: Owner ID:None
17:35:39 T:1551830504   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 7] no address associated with hostname.>
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livestream-master/main.py", line 424, in <module>
                                                SEARCH_LIVE()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livestream-master/main.py", line 147, in SEARCH_LIVE
                                                json_source = SEARCH()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.livestream-master/main.py", line 137, in SEARCH
                                                response = urllib2.urlopen(req,json_search)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 126, in urlopen
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 391, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 409, in _open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 1161, in http_open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/urllib2.py", line 1136, in do_open
                                            URLError: <urlopen error [Errno 7] no address associated with hostname.>
                                            -->End of Python script error report<--
17:35:39 T:1505011360   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.livestream/?icon=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.livestream-master%2ficon.png&mode=102&name=Search%20Live&url=%2fsearch
17:35:39 T:1505011360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.livestream/?icon=%2fstorage%2femulated%2f0%2fAndroid%2fdata%2forg.xbmc.kodi%2ffiles%2f.kodi%2faddons%2fplugin.video.livestream-master%2ficon.png&mode=102&name=Search%20Live&url=%2fsearch) failed
17:35:39 T:1666559720  NOTICE: Thread LanguageInvoker start, auto delete: false
17:35:39 T:1666559720  NOTICE: -->Python Interpreter Initialized<--
17:35:39 T:1666559720  NOTICE: Mode: None
17:35:39 T:1666559720  NOTICE: Name: None
17:35:39 T:1666559720  NOTICE: Event ID:None
17:35:39 T:1666559720  NOTICE: Owner ID:None
17:35:39 T:1669718632  NOTICE: Thread BackgroundLoader start, auto delete: false
17:35:41 T:1662773320  NOTICE: Thread LanguageInvoker start, auto delete: false
17:35:41 T:1662773320  NOTICE: -->Python Interpreter Initialized<--
17:35:42 T:1662773320  NOTICE: Mode: 100
17:35:42 T:1662773320  NOTICE: Name: Live & Upcoming
17:35:42 T:1662773320  NOTICE: Event ID:None
17:35:42 T:1662773320  NOTICE: Owner ID:None```

Here's the error I get when I try to search.
``````
